version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017" #erro 4
    volumes:
      - /tmp/data:/data/db
  app:
    build: ./app
    ports:
      - "3000:3000" #erro 5
    depends_on:
      - mongodb
    restart: always