version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
  index:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: always