services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      interval: 30s
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
      retries: 3
      start_period: 10s
      timeout: 10s

  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    restart: always

volumes:
  mongo-data:
