version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - /tmp/data:/data/db
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    restart: always