version: '3.8'

services:
  
  mongo:
    image: mongo:latest
    volumes:
      - /tmp/data:/data/db
    networks:
      - app-network
  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/desafio
      - PORT=3000
    depends_on:
      - mongodb
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongodb-data:    