version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb         
    ports:
      - "27017:27017"                     
    restart: unless-stopped         

  app:
    build:
      context: ./app           
    ports:
      - "3000:3000"             
    depends_on:
      - mongodb
    restart: unless-stopped
    environment:
      - mongoURI = 'mongodb://mongo:27017/desafio'