services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./app/volume_data:/app/data 
    restart: always

volumes:
  mongodb_data: