version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    restart: always

volumes:
  mongodbdata:
