version: '3.8'

services:
  mongodb:
    image: mongodb:latest
    ports:
      - "27017:27017"
    volumes:
       - mongo-data:/data/db
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/jogo7erros
    restart: always    
volumes:
  mongo-data:
